### ISSUE TITLE
SoapUI Integration

### ISSUE THREAD

**Issue by filypsdias** [kinow/testlink-java-api#105] opened 2018-06-11 15:25 UTC
Hi. I'm running a new SoapUI project and i'm trying to transfer the testCase values into a TestLink project. Is it possible to do that? If it is, can someone help me with it?

I want to save a JDBC and REST Requests. 
Thx.

**Comment by kinow** [comment] 2019-04-08 01:08
Hi @filypsdias 

It should be doable, I think someone did something similar in the past using this same API, but it was with an older version of TestLink. Not sure if the API is compatible with the latest version (see #120 comments).

You would have to extend SoapUI to report on the success/failure using the API and post to TestLink PHP.

If you find issues using the Java API, feel free to report the bug here. Try to include as much information as possible so others can reproduce your issue too 👍 

Closing as not a bug.
Bruno

**Closed by kinow** 2019-04-08 01:08 UTC
